[phases.setup]
nixPkgs = ["nodejs-18_x"]
aptPkgs = ["openssl"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npx prisma generate", "cd backend && npm run build"]

[start]
cmd = "cd backend && node dist/server.js"
